name: Sync GitHub to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Agentic Medical Image Analyzer Repo
        uses: actions/checkout@v4
        with:
          repository: MohibAhmadButt/Agentic-Medical-Image-Analyzer
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync to Hugging Face Hub
        uses: huggingface/hub-sync@latest
        with:
          github_repo_id: MohibAhmadButt/Agentic-Medical-Image-Analyzer
          huggingface_repo_id: MohibAhmadButt/Agentic-Medical-Image-Analyzer
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: docker
