name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # REPLACE 'MohibAhmadButt' and 'Agentic-Medical-Image-Analyzer' if different
          git push --force https://MohibAhmadButt:$HF_TOKEN@huggingface.co/spaces/MohibAhmadButt/Agentic-Medical-Image-Analyzer main
